'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Almacen
    Public Property Sku As Integer
    Public Property Pieza As String
    Public Property Existencias As Nullable(Of Integer)
    Public Property Faltantes As Nullable(Of Integer)
    Public Property NombreAlmacen As String
    Public Property PedidoSurtido As String
    Public Property PedidoCotejado As String
    Public Property PedidoEnviado As String
    Public Property FechaEnvio As Nullable(Of Date)
    Public Property FechaSurtido As Nullable(Of Date)

End Class
