'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catalogolars
    Public Property Sku As String
    Public Property Nombre As String
    Public Property Tamaño As String
    Public Property PrecioCosto As String
    Public Property PrecioLocal As Nullable(Of Double)
    Public Property PrecioForaneo As Nullable(Of Double)
    Public Property PrecioBarra As Nullable(Of Double)

End Class
