'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inventario
    Public Property Sku As Integer
    Public Property CodigoAlterno As String
    Public Property Vendidos As String
    Public Property PorSurtir As String
    Public Property TotalPiezas As Nullable(Of Integer)
    Public Property Almacen As Nullable(Of Integer)
    Public Property FechaUltimaActualizacion As Nullable(Of Date)

End Class
