'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class masterEntities2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=masterEntities2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property MSreplication_options() As DbSet(Of MSreplication_options)
    Public Overridable Property spt_fallback_db() As DbSet(Of spt_fallback_db)
    Public Overridable Property spt_fallback_dev() As DbSet(Of spt_fallback_dev)
    Public Overridable Property spt_fallback_usg() As DbSet(Of spt_fallback_usg)
    Public Overridable Property spt_monitor() As DbSet(Of spt_monitor)
    Public Overridable Property spt_values() As DbSet(Of spt_values)
    Public Overridable Property Almacen() As DbSet(Of Almacen)
    Public Overridable Property carrusel() As DbSet(Of carrusel)
    Public Overridable Property catalogolars() As DbSet(Of catalogolars)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property Inventario() As DbSet(Of Inventario)
    Public Overridable Property NewProducto() As DbSet(Of NewProducto)
    Public Overridable Property Pedido() As DbSet(Of Pedido)
    Public Overridable Property ProveedorWinmex() As DbSet(Of ProveedorWinmex)
    Public Overridable Property PrecioCliente() As DbSet(Of PrecioCliente)
    Public Overridable Property Producto() As DbSet(Of Producto)
    Public Overridable Property ProductoNegado() As DbSet(Of ProductoNegado)
    Public Overridable Property Ventas() As DbSet(Of Ventas)

    Public Overridable Function sp_MScleanupmergepublisher() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher")
    End Function

    Public Overridable Function sp_MSrepl_startup() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_MSrepl_startup")
    End Function

End Class
