'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pedido
    Public Property IdCliente As Integer
    Public Property Folio As Nullable(Of Integer)
    Public Property AreaCotejo As String
    Public Property PersonaSurtido As String
    Public Property StatusPedido As String
    Public Property VerificacionPedido As String
    Public Property RutaAsignada As String
    Public Property ChoferAsignado As String
    Public Property Total As Nullable(Of Decimal)
    Public Property FechaPedido As Nullable(Of Date)
    Public Property Pedido1 As String
    Public Property PersonaAutoriza As String

End Class
