'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property CodigoAlterno As String
    Public Property Sku As String
    Public Property Descripcion As String
    Public Property Precio As Nullable(Of Double)
    Public Property Existencias As Nullable(Of Integer)
    Public Property Marca As String
    Public Property Vendidos As Nullable(Of Integer)
    Public Property PorSurtir As Nullable(Of Integer)
    Public Property Proveedor As String
    Public Property Almacen As String
    Public Property TotalPiezas As Nullable(Of Integer)
    Public Property Categoria As String
    Public Property ClaveProdServ As String
    Public Property ClaveUnidad As String
    Public Property Compatibilidad As String
    Public Property FechaActualizacion As Nullable(Of Date)
    Public Property Imagen As String
    Public Property Detalles As String

End Class
