'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductoNegado
    Public Property Sku As String
    Public Property NombreCliente As String
    Public Property CantidadNegada As Nullable(Of Integer)
    Public Property FechaNegacion As Nullable(Of Date)
    Public Property Motivo As String
    Public Property FolioPedido As Nullable(Of Integer)
    Public Property Detalles As String

End Class
