'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProveedorWinmex
    Public Property Sku As String
    Public Property CodigoAlterno As String
    Public Property Descripcion As String
    Public Property PrecioCosto As Nullable(Of Double)
    Public Property Precio1 As Nullable(Of Double)
    Public Property Precio2 As Nullable(Of Double)
    Public Property Precio3 As Nullable(Of Double)
    Public Property Precio4 As Nullable(Of Double)
    Public Property Iva As Nullable(Of Double)
    Public Property ieps As Nullable(Of Double)
    Public Property Tipo As String
    Public Property Categoria As String
    Public Property Marca As String
    Public Property Proveedor As String
    Public Property Existencia As String
    Public Property Almacen As String
    Public Property ClaveProdServ As String
    Public Property ClaveUnidad As String

End Class
