'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ventas
    Public Property IdCliente As String
    Public Property Folio As Nullable(Of Integer)
    Public Property FormaPago As String
    Public Property TipoPago As String
    Public Property FechaCompra As Nullable(Of Date)
    Public Property FechaSurtido As Nullable(Of Date)
    Public Property Total As Nullable(Of Double)
    Public Property Codigo As String
    Public Property TipoVenta As String
    Public Property Vendedor As String

End Class
